"""Resume LaTeX composition and PDF rendering.

Composes ordered :class:`~job_dashboard.resume.segments.Segment` blocks into
a full LaTeX document (splicing their ``.text`` between body markers in a
template), then renders that document to a PDF via an injectable runner.
The default runner shells out to a real ``lualatex`` binary; tests inject a
fake runner so no LaTeX toolchain is required for unit coverage.
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path
from typing import Callable

from job_dashboard.resume.segments import Segment

# Marker lines the composed body is spliced between. Kept as plain LaTeX
# comments so they are inert if ever left in a compiled document.
BODY_START_MARKER = "% RESUME_BODY_START"
BODY_END_MARKER = "% RESUME_BODY_END"

# Clean single-column article-class template. Replaces the previous
# moderncv "banking" template: moderncv's multi-column/icon-font styling is
# fragile under lualatex (fontawesome5 glyphs silently fall back to plain
# text like "MOBILE-ALT" when the icon font isn't fully resolved) and is
# generally worse for ATS parsing than a plain single-column layout. Segment
# blocks (resume_segments/*.tex) are plain \section + \item/itemize LaTeX
# compatible with this template — no moderncv commands (\cventry, \cvitem,
# \name, \makecvtitle, ...) should remain anywhere in the segment library.
DEFAULT_TEMPLATE = r"""%% Resume — generated by job_dashboard.resume.render
%% Compile with: lualatex

\documentclass[11pt,a4paper]{article}
\usepackage[left=0.75in,right=0.75in,top=0.6in,bottom=0.6in]{geometry}
\usepackage[T1]{fontenc}
\usepackage{lmodern}
\usepackage{fontawesome5}
\usepackage{hyperref}
\hypersetup{
    colorlinks=true,
    linkcolor=black,
    urlcolor=blue,
    pdftitle={Rakshit Singh - Resume},
    pdfpagemode=UseNone,
}
\usepackage{enumitem}
% Compact bullets with a small dot marker, matching the source résumé.
\setlist[itemize]{leftmargin=1.4em, itemsep=1pt, topsep=2pt, parsep=0pt,
                  label=\raisebox{0.15ex}{\scriptsize$\bullet$}}
\usepackage{titlesec}
% Bold, mixed-case section headings with a full-width rule underneath.
\titleformat{\section}{\large\bfseries}{}{0em}{}[\vspace{-3pt}\titlerule\vspace{1pt}]
\titlespacing*{\section}{0pt}{9pt}{4pt}

\pagestyle{empty}
\setlength{\parindent}{0pt}

\begin{document}

""" + BODY_START_MARKER + "\n" + BODY_END_MARKER + r"""

\end{document}
"""

# Real lualatex binary, as installed by MacTeX on this machine.
TEXBIN_LUALATEX = Path("/Library/TeX/texbin/lualatex")

Runner = Callable[[Path, Path], Path]


def compose(blocks: list[Segment], template: str = DEFAULT_TEMPLATE) -> str:
    """Splice each block's ``.text`` into ``template`` between body markers.

    Blocks are inserted in the order given, joined by blank lines. Raises
    ``ValueError`` if the template is missing either marker.
    """
    if BODY_START_MARKER not in template or BODY_END_MARKER not in template:
        raise ValueError(
            f"template is missing body markers {BODY_START_MARKER!r} / {BODY_END_MARKER!r}"
        )

    start = template.index(BODY_START_MARKER) + len(BODY_START_MARKER)
    end = template.index(BODY_END_MARKER)
    body = "\n\n".join(block.text for block in blocks)
    return template[:start] + "\n" + body + "\n" + template[end:]


def lualatex_path() -> str:
    """Resolve the lualatex binary, preferring the MacTeX texbin install.

    Raises ``RuntimeError`` with a clear message if no lualatex binary can
    be found anywhere.
    """
    if TEXBIN_LUALATEX.exists():
        return str(TEXBIN_LUALATEX)
    found = shutil.which("lualatex")
    if found:
        return found
    raise RuntimeError("lualatex not found — install MacTeX")


def _extract_log_tail(log_path: Path, context_lines: int = 20) -> str:
    """Return the most useful slice of a lualatex .log for an error message.

    LaTeX errors (lines starting with ``!``) can sit well before the trailing
    font-loading/memory-stats noise that nonstopmode still prints even after
    a fatal-to-us error, so a plain last-N-lines tail can miss the actual
    error. Prefer the first ``!`` line found plus surrounding context; fall
    back to the last lines of the log if no such marker is present.
    """
    if not log_path.exists():
        return "(no log file found)"

    lines = log_path.read_text(errors="replace").splitlines()
    error_idx = next((i for i, line in enumerate(lines) if line.startswith("!")), None)
    if error_idx is not None:
        end = min(len(lines), error_idx + context_lines)
        return "\n".join(lines[error_idx:end])
    return "\n".join(lines[-40:])


def _run_lualatex(tex_path: Path, out_dir: Path) -> Path:
    """Real lualatex runner: two passes, nonstop mode, raise on failure."""
    binary = lualatex_path()
    for _ in range(2):
        result = subprocess.run(
            [
                binary,
                "-interaction=nonstopmode",
                f"-output-directory={out_dir}",
                str(tex_path),
            ],
            cwd=out_dir,
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            log_path = out_dir / (tex_path.stem + ".log")
            tail = _extract_log_tail(log_path)
            raise RuntimeError(
                f"lualatex failed (exit {result.returncode}) compiling {tex_path.name}.\n"
                f"--- compile log tail ---\n{tail}"
            )

    pdf_path = out_dir / (tex_path.stem + ".pdf")
    if not pdf_path.exists():
        raise RuntimeError(
            f"lualatex reported success but no PDF was produced at {pdf_path}"
        )
    return pdf_path


def render_pdf(tex: str, out_dir: Path | str, runner: Runner | None = None) -> Path:
    """Write ``tex`` to ``out_dir`` and render it to a PDF.

    ``runner(tex_path, out_dir) -> pdf_path`` performs the actual
    compilation; it defaults to the real lualatex runner (two passes,
    nonstop mode). Returns the path to the produced PDF.

    ``out_dir`` is resolved to an absolute path before use. The real runner
    passes it both as ``cwd`` and as ``-output-directory``; if it were left
    relative, lualatex would resolve ``-output-directory`` against its
    already-changed cwd and try to create a doubly-nested directory (e.g.
    ``data/resumes/data/resumes``), fail immediately, and exit without ever
    writing a .log file — surfacing as an opaque "no log file found" error
    with no real diagnostic.
    """
    out_dir = Path(out_dir).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    tex_path = out_dir / "resume.tex"
    tex_path.write_text(tex)

    if runner is None:
        runner = _run_lualatex

    return runner(tex_path, out_dir)
