"""Cover-letter LaTeX composition and PDF rendering.

Reuses :func:`job_dashboard.resume.render.render_pdf` for the actual LaTeX
compilation — same injectable ``runner`` seam, same ``lualatex_path``
resolution, same two-pass nonstop-mode behavior. This module only owns the
letter-specific template and body splicing; it does not shell out to
lualatex itself.
"""

from __future__ import annotations

from pathlib import Path
from typing import Callable

from job_dashboard.resume.render import render_pdf

# Placeholder token the (escaped) letter body is spliced in for.
BODY_TOKEN = "%%BODY%%"

# Clean single-column article-class letter template — ATS-safe, same spirit
# as job_dashboard.resume.render.DEFAULT_TEMPLATE (no moderncv/letter-class
# fanciness that can render inconsistently or confuse ATS parsers).
LETTER_TEMPLATE = r"""%% Cover letter — generated by job_dashboard.letter.render_letter
%% Compile with: lualatex

\documentclass[11pt,a4paper]{article}
\usepackage[margin=1in]{geometry}
\usepackage[T1]{fontenc}
\usepackage{lmodern}
\usepackage{hyperref}
\hypersetup{
    colorlinks=true,
    linkcolor=blue,
    urlcolor=blue,
    pdftitle={Cover Letter},
    pdfpagemode=UseNone,
}

\pagestyle{empty}
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt}

\begin{document}

\today

Hiring Manager \\
Company

\vspace{12pt}

""" + BODY_TOKEN + r"""

\vspace{12pt}

Sincerely, \\{}
[Your Name]

\end{document}
"""

Runner = Callable[[Path, Path], Path]


def _latex_escape(text: str) -> str:
    """Escape LaTeX special characters that commonly appear in prose body text.

    Handles ``& % $ _ # { }``. Paragraph breaks (blank lines, ``\\n\\n``) are
    left untouched — plain LaTeX already treats a blank line as a new
    paragraph, so no ``\\par`` insertion is needed. None of the replacement
    strings below contain another of the escaped characters, so applying
    them in sequence (rather than a single combined pass) cannot double-escape.
    """
    replacements = {
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "_": r"\_",
        "#": r"\#",
        "{": r"\{",
        "}": r"\}",
    }
    for char, escaped in replacements.items():
        text = text.replace(char, escaped)
    return text


def render_letter_pdf(body: str, out_dir: Path | str, runner: Runner | None = None) -> Path:
    """Splice ``body`` (LaTeX-escaped) into :data:`LETTER_TEMPLATE` and render it.

    Reuses :func:`job_dashboard.resume.render.render_pdf` for composition-to-disk
    and compilation, so the injectable ``runner`` and real-lualatex behavior
    (including its ``lualatex_path`` resolution) are identical to the resume
    renderer. Returns the path to the produced PDF.
    """
    escaped_body = _latex_escape(body)
    tex = LETTER_TEMPLATE.replace(BODY_TOKEN, escaped_body)
    return render_pdf(tex, out_dir, runner=runner)
